# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2942029145ab8dc624f23d32e32e002c0dfe365a61f52998bb8f6389166776de9b59f46f55a518d6ae10319a6e53b84061d93f23ceca86e787103119321822c

test:
  secret_key_base: 11531e655e75179e766b13598ecb32f54bd92a311bafe5e8ff86c276d9e51742cbb084388466f3e2405a47893490e3b60f3931101e27b5750da9422fc90ecbd3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
